require('../../dotenv/config')
console.log('==================================================')
console.log(process.env.NODE_ENV)
console.log(process.env.MONGO_URI)
console.log('==================================================')